on:
  pull_request:
    types: [closed]
    paths:
      - 'requests/**'
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: get branch
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: get environment name
        run: |
          output=$(python get_env_name.py)
          echo "::set-output name=env-name::$output"
        env:
          BRANCH_NAME: ${{ steps.branch-name.outputs.current_branch }}
          PR_NUM: ${{ github.event.number }}
        id: get-env-name
      - run: echo ${{ steps.get-env-name.outputs.env-name }}
      - name: delete environment
        run: |
          echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token
          gh api --method DELETE -H "Accept: application/vnd.github.v3+json" /repos/aarongh2012/actions-testing/environments/${{ steps.get-env-name.outputs.env-name }}
          