on:
  pull_request:
    types: [closed]
    paths:
      - 'requests/**'
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: get branch
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: get environment name
        run: python get_env_name.py
        env:
          BRANCH_NAME: ${{ steps.branch-name.outputs.current_branch }}
          PR_NUM: ${{ github.event.number }}
      - run: echo $GH_ENV_NAME
      - name: delete environment
        run: |
          gh auth login
          gh api --method DELETE -H "Accept: application/vnd.github.v3+json" /repos/aarongh2012/actions-testing/environments/${{ env.GH_ENV_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}