on:
  pull_request:
    types: [closed]
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: get branch
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - run: echo "${{ steps.branch-name.output.current_branch }}"
      - run: echo ${{github.event.number}}