on:
  pull_request:
    types: [opened]
jobs:
  open_issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo open request
      - name: get output
        id: open_issue
        run: |
          echo open issue
      - name: close pr
        - uses: peter-evans/close-pull@v2.0.0
          with:
            comment: "blah blah blah blah"
            delete-branch: true