on:
  pull_request:
    types: [opened]
jobs:
  open_issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo open request
      - name: Open issue
        run: |
          echo "::set-output name=url::test"
        id: set-output