on:
  pull_request:
    types: [opened]
    paths:
      - 'requests/**'
jobs:
  open_issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo open request
      - name: Open issue
        run: |
          echo "::set-output name=url::test"
        id: set-output
      - name: Add PR Comment
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: ${{ steps.set-output.outputs.url }}
